name: Build

# Trigger on any push/pull request to master
on:
  push:
    branches:
      - master
      - QA-installer
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest # Must be windows as we only target windows machines
    strategy:
      matrix:
        python-version: [3.8] # Can be expanded to multiple Python versions
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Checkout PyInstaller repo
      uses: actions/checkout@v2
      with:
        repository: pyinstaller/pyinstaller
        ref: master
    - name: Install PyInstaller from source with generated bootloader # This is needed to prevent antivirus false positive: https://stackoverflow.com/a/52054580
      run: |
        cd bootloader
        python ./waf all
        cd ..
        python setup.py install
    - name: Checkout AN32X_Installer repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -r requirements.txt
    - name: Build executable
      run: |
        pyinstaller Downloader.spec
        Compress-Archive -Path dist\* -DestinationPath A32NX_Downloader.zip
    - name: Check AV status
      run: |
        python CheckAVStatus.py
      env:
        VIRUS_TOTAL_API_KEY: ${{ secrets.VIRUS_TOTAL_API_KEY }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: A32NX_Downloader.zip
        path: dist/A32NX_Downloader_QA_Version.exe