name: Build

# Trigger on any push/pull request to master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest # Must be windows as we only target windows machines
    strategy:
      matrix:
        python-version: [3.8] # Can be expanded to multiple Python versions
    steps:
    - name: Checkout AN32X_Installer repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Checkout PyInstaller repo
      uses: actions/checkout@v2
      with:
        repository: pyinstaller/pyinstaller
        ref: master
    - name: Install PyInstaller from source with generated bootloader # This is needed to prevent antivirus false positive: https://stackoverflow.com/a/52054580
      run: |
        cd bootloader
        python ./waf all
        cd ..
        python setup.py install
    - name: Checkout AN32X_Installer repo again
      uses: actions/checkout@v2
    - name: Build the executable
      run: |
        pyinstaller Downloader.spec
